### ISSUE TITLE
[guild.id] must be of type integer Error becouse guild.id is a integer

### ISSUE THREAD

**Issue by Sawaya-ui** [restcord/restcord#169]
Hello everytime I try to get a Guild Member I get this error:
`
2021-12-01 01:08:58: mod_fastcgi.c.487) FastCGI-stderr:PHP Fatal error:  Uncaught GuzzleHttp\Command\Exception\CommandException: Validation errors: [guild.id] must be of type integer
2021-12-01 01:08:58: mod_fastcgi.c.487) FastCGI-stderr:[user.id] must be of type integer in /var/www/html/********/vendor/guzzlehttp/guzzle-services/src/Handler/ValidatedDescriptionHandler.php:76
2021-12-01 01:08:58: mod_fastcgi.c.487) FastCGI-stderr:Stack trace:
2021-12-01 01:08:58: mod_fastcgi.c.487) FastCGI-stderr:#0 /var/www/html/********/vendor/guzzlehttp/command/src/ServiceClient.php(85): GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}()
2021-12-01 01:08:58: mod_fastcgi.c.487) FastCGI-stderr:#1 /var/www/html/********/vendor/guzzlehttp/command/src/ServiceClient.php(77): GuzzleHttp\Command\ServiceClient->executeAsync()
2021-12-01 01:08:58: mod_fastcgi.c.487) FastCGI-stderr:#2 /var/www/html/********/vendor/guzzlehttp/command/src/ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute()
2021-12-01 01:08:58: mod_fastcgi.c.487) FastCGI-stderr:#3 /var/www/html/********/vendor/restcord/restcord/src/OverriddenGuzzleClient.php(86): GuzzleHttp\Command\ServiceClient->__call()
2021-12-01 01:08:58: mod_fastcgi.c.487) FastCGI-stderr:#4 /var/www/html/********/user/login.php(40): RestCord\OverriddenGuzzleClient->__call()
2021-12-01 01:08:58: mod_fastcgi.c.487) FastCGI-stderr:#5 {main}
2021-12-01 01:08:58: mod_fastcgi.c.487) FastCGI-stderr:  thrown in /var/www/html/********/vendor/guzzlehttp/guzzle-services/src/Handler/ValidatedDescriptionHandler.php on line 76
`
**Code:**
`
var_dump($client->guild->getGuildMember(['guild.id' => 909599485204779028, 'user.id' => $_SESSION['uid']]));
`
**PHP Version: 7.4**
**RestCord Version: dev-develop**

**Comment by LeigerGaming** [comment]
It's also reporting that `user.id` should be an integer. Does it work if you hard-code the User ID as an integer? Perhaps it's being retrieved from the session as something else like a string.

You could try:
```php
intval($_SESSION['uid'])
```

**Comment by kirihito-kun** [comment]
If you use $_SESSION you have to put (int) before it.

**Comment by Sawaya-ui** [comment]
thx forget to close it lmao
