### ISSUE TITLE
403 Getting Guild Info / Channel Messages

### ISSUE THREAD

**Issue by ChrisYatesUK** [restcord/restcord#177]
OK so my bot requires the scopes : read messages & message history
Permission integer :66560 
The bot has been authorised using the generated link by the server owner
I have tested it on the test server I created for test messages and it works however when I try it with the other server
that its just been authorised on it gives a 403

$discord = new DiscordClient(['token' => 'My Token Here','tokenType' => 'Bot']);
$channel = 933010260027932735; // My Channel
$main = 924525404658749500; // Channel trying to pull
print_r($discord->channel->getChannelMessages(['channel.id' => $channel]))
Gives me the JSON data
However when I change it to $main I get this error
Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://discord.com/api/v6/channels/924525404658749500/messages` resulted in a `403 Forbidden` response:

 in /home/chrisyat/public_html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /home/chrisyat/public_html/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/chrisyat/public_html/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/chrisyat/public_html/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), NULL)
#3 /home/chrisyat/public_html/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/chrisyat/public_html/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(118):  in /home/chrisyat/public_html/vendor/guzzlehttp/command/src/Exception/CommandException.php on line 57

The same when  try and pull the guild info

I know he authorised it because I got the auth redirect page to create a dump with the server info upon successful token creation

Its driving me crazy now so any help is greatly appreciated

**Comment by ChrisYatesUK** [comment]
Also on the redirect url after the person clicks the authorisation link 
Am I right to assume the 
 'client_id' => OAUTH2_CLIENT_ID,
 'client_secret' => OAUTH2_CLIENT_SECRET,
 needs to be the values in the bot OAUTH page ?

**Comment by cryptiklemur** [comment]
The same request worked in one guild and returned 403 in another, which points to Discord channel or guild permissions rather than request construction. RestCord 0.9.0 sends the configured Bot authorization header. Please open a new issue with a minimal 0.9.0 reproduction if a client defect remains.
