### ISSUE TITLE
RestCord doesn't work on Windows

### ISSUE THREAD

**Issue by andre-paulo98** [restcord/restcord#19]
Tried to run the first example from the docs:
```
<?php
include __DIR__.'/vendor/autoload.php';
use RestCord\DiscordClient;
$discord = new DiscordClient(['token' => 'bot-token']); // Token is required
var_dump($discord->guild->getGuild(['guild.id' => 81384788765712384])); // i changed the id
```
Everytime doesn't matter what i got:
```
Fatal error:  Uncaught GuzzleHttp\Command\Exception\CommandException: Validation errors: [guild.id] must be of type integer in C:\xampp\htdocs\folder\vendor\guzzlehttp\guzzle-services\src\Handler\ValidatedDescriptionHandler.php:76
Stack trace:
#0 C:\xampp\htdocs\folder\vendor\guzzlehttp\command\src\ServiceClient.php(85): GuzzleHttp\Command\Guzzle\Handler\ValidatedDescriptionHandler->GuzzleHttp\Command\Guzzle\Handler\{closure}(Object(GuzzleHttp\Command\Command))
#1 C:\xampp\htdocs\folder\vendor\guzzlehttp\command\src\ServiceClient.php(77): GuzzleHttp\Command\ServiceClient->executeAsync(Object(GuzzleHttp\Command\Command))
#2 C:\xampp\htdocs\folder\vendor\guzzlehttp\command\src\ServiceClient.php(153): GuzzleHttp\Command\ServiceClient->execute(Object(GuzzleHttp\Command\Command))
#3 C:\xampp\htdocs\folder\discordbot.php(10): GuzzleHttp\Command\ServiceClient->__call('getGuild', Array)
#4 {main}
  thrown in C:\xampp\htdocs\folder\vendor\guzzlehttp\guzzle-services\src\Handler\ValidatedDescriptionHandler.php on line 76
```

Then i tried to run the same script on Ubuntu and it worked first time.
**PHP Version on Ubuntu**: PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
**PHP Version local**: PHP 7.0.9 (cli) (built: Jul 20 2016 11:08:23) ( ZTS )

**Comment by aequasi** [comment]
It requires 64bit PHP to run.

**Comment by andre-paulo98** [comment]
Checked and i have 32bit installed locally and 64 on the server.
Thank you

**Comment by KevTheCrafter** [comment]
Can you please add this information to the documentation?

**Comment by aequasi** [comment]
https://github.com/restcord/restcord/commit/9d924cdacbb76ebff0099c1c15d193c63ffb000a
