### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Werwi** [restcord/restcord#42]
Hi, please help.. (btw. sorry for my english, my english is bad)
Here is my code:
```
include __DIR__.'/vendor/autoload.php';

use RestCord\DiscordClient;

$discord = new DiscordClient(['token' => 'auth token']); // Token is required

var_dump($discord->channel->createMessage(['channel.id' => 403283706615169025, 'content' => 'Foo Bar Baz']));
var_dump(
    $client->channel->createMessage([
         'channel.id' => $channelId,
         'content'    => "this `supports` __a__ **subset** *of* ~~markdown~~ 😃 ```js
 function foo(bar) {
   console.log(bar);
 }
 
 foo(1);```",
         'embed'      => [
             "title" => "title ~~(did you know you can have markdown here too?)~~",
             "description" => "this supports [named links](https://discordapp.com) on top of the previously shown subset of markdown. ```\nyes, even code blocks```",
             "url" => "https://discordapp.com",
             "color" => 14290439,
             "timestamp" => "2017-02-20T18:05:58.512Z",
             "footer" => [
                 "icon_url" => "https://cdn.discordapp.com/embed/avatars/0.png",
                 "text" => "footer text"
             ],
             "thumbnail" => [
                 "url" => "https://cdn.discordapp.com/embed/avatars/0.png"
             ],
             "image" => [
                 "url" => "https://cdn.discordapp.com/embed/avatars/0.png"
             ],
             "author" => [
                 "name" => "author name",
                 "url" => "https://discordapp.com",
                 "icon_url" => "https://cdn.discordapp.com/embed/avatars/0.png"
             ],
             "fields" => [
                 [
                     "name" => "Foo",
                     "value" => "some of these properties have certain limits..."
                 ],
                 [
                     "name" => "Bar",
                     "value" => "try exceeding some of them!"
                 ],
                 [
                     "name" => " 😃",
                     "value" => "an informative error should show up, and this view will remain as-is until all issues are fixed"
                 ],
                 [
                     "name" => "<:thonkang:219069250692841473>",
                     "value" => "???"
                 ]
             ]
         ]
     ])
 );
```

500 error:
```
[2018-02-10 22:07:18] Logger.INFO: https://discordapp.com/api/v6/channels/403283894784491550/messages POST /api/v6/channels/403283894784491550/messages HTTP/1.1 Content-Length: 37 Authorization: Bot <TOKEN> User-Agent: DiscordBot (https://github.com/aequasi/php-restcord, 0.1.1) Host: discordapp.com Content-Type: application/json  {"content":"Foo Bar Baz","tts":false} [] []
[2018-02-10 22:07:18] Logger.INFO: HTTP/1.1 400 BAD REQUEST Date: Sat, 10 Feb 2018 22:07:18 GMT Content-Type: application/json Content-Length: 42 Connection: keep-alive Set-Cookie: __cfduid=d0e1bd83467024ab53c3b24f7284e8c371518300437; expires=Sun, 10-Feb-19 22:07:17 GMT; path=/; domain=.discordapp.com; HttpOnly Strict-Transport-Security: max-age=31536000; includeSubDomains X-RateLimit-Limit: 5 X-RateLimit-Remaining: 3 X-RateLimit-Reset: 1518300439 Via: 1.1 google Alt-Svc: clear Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct" Server: cloudflare CF-RAY: 3eb2616918223e20-PRG  {"code": 40001, "message": "Unauthorized"} [] []
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `POST https://discordapp.com/api/v6/channels/403283894784491550/messages` resulted in a `400 BAD REQUEST` response:

 in /var/werwi/main/conybot/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/werwi/main/conybot/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/werwi/main/conybot/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/werwi/main/conybot/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/werwi/main/conybot/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/werwi/main/conybot/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(96): GuzzleHttp\P in /var/werwi/main/conybot/vendor/guzzlehttp/command/src/Exception/CommandException.php on line 57
```
Thanks in advance!

**Comment by aequasi** [comment]
I've copy-pasted this code, and after supplying $channelId, can run this with no issue. Make sure you're up to date on the latest `dev-develop`.
