### ISSUE TITLE
Rate limiter exception

### ISSUE THREAD

**Issue by Skyedra** [restcord/restcord#53]
When sending many requests quickly, rate limiting throws an exception, even if 'throwOnRatelimit' is set to false.

> PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://discordapp.com/api/v6/guilds/XXXX/members?limit=10&after=XXXX` resulted in a `429 TOO MANY REQUESTS` response:
> 
>  in /XXXX/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
> Stack trace:
> #0 /XXXX/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
> #1 /XXXX/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
> #2 /XXXX/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
> #3 /XXXX/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Prom in /XXXX/vendor/guzzlehttp/command/src/Exception/CommandException.php on line 57

**Comment by warlof** [comment]
Hi,

I think it's handled by the library. But it need to be instantiate as a singleton.
I'm unsure; and quite interested by an official answer :p

https://github.com/restcord/restcord/blob/master/src/DiscordClient.php#L75-L80

**Comment by sky-lake** [comment]
I was poking around (very!) briefly, and it looks like maybe there is support for rate limiting _predictively_ based on parsing the headers of responses, but when rate limiting is actually tripped / errored by the server, it doesn't wait and retry the request.  If that is the case, the ideal solution may be a mix of 1) finding out why the predictive limiting isn't working as well as 2) adding retry after delay support when rate limiting is tripped.

**Comment by cryptiklemur** [comment]
RestCord 0.9.0 waits for known capacity and retries Discord 429 responses by default. Set throwOnRatelimit to receive RatelimitException immediately. Shared Redis coordination is also supported and tested.
