### ISSUE TITLE
$client->channel->editMessage fatal error

### ISSUE THREAD

**Issue by MattIPv4** [restcord/restcord#62]
This traceback occurs 
```
<b>Fatal error</b>:  Uncaught Error: Class '\RestCord\Model\Channel\ISO8601' not found in /Users/[REDACTED]/PhpstormProjects/[REDACTED]/vendor/netresearch/jsonmapper/src/JsonMapper.php:554
--
  | Stack trace:
  | #0 /Users/[REDACTED]/PhpstormProjects/[REDACTED]/vendor/netresearch/jsonmapper/src/JsonMapper.php(274): JsonMapper-&gt;createInstance('\\RestCord\\Model...', true, '2018-08-26T13:4...')
  | #1 /Users/[REDACTED]/PhpstormProjects/[REDACTED]/vendor/restcord/restcord/src/DiscordClient.php(270): JsonMapper-&gt;map(Object(stdClass), Object(RestCord\Model\Channel\Message))
  | #2 /Users/[REDACTED]/PhpstormProjects/[REDACTED]/vendor/restcord/restcord/src/DiscordClient.php(183): RestCord\DiscordClient-&gt;convertResponseToResult('channel', Array, Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Command\Command))
  | #3 /Users/[REDACTED]/PhpstormProjects/[REDACTED]/vendor/guzzlehttp/command/src/ServiceClient.php(215): RestCord\DiscordClient-&gt;RestCord\{closure}(Object(GuzzleHttp\Psr7\Response), Object(Guzz in <b>/Users/[REDACTED]/PhpstormProjects/[REDACTED]/vendor/netresearch/jsonmapper/src/JsonMapper.php</b> on line <b>554</b><br />
```
when running
```
$msg = $bot->channel->editMessage(["channel.id" => BOT_LISTS, "message.id" => $res, "content" => $content]);
```
where `BOT_LISTS` is an integer, `$res` is an integer and `$content` is a string under 2000 chars.

Any ideas?

**Comment by aequasi** [comment]
Fixed in 18e7e802966e2c2f460c624e98d4636967f58c29
