### ISSUE TITLE
Error 403 on guild->modifyGuildMember

### ISSUE THREAD

**Issue by sky-lake** [restcord/restcord#94]
Hello,

I'm suddenly getting this error today on calling `guild->modifyGuildMember`.  I know my script worked at least as recently as 8/11, but discovered today (8/23) it was failing.  My `guild->listGuildMembers` still seems to work.

On this command:

```
                $result = $discord->guild->modifyGuildMember([
                        'guild.id' => skyDiscord\getDiscordServerID(),
                        'user.id' => $discordID,
                        'roles' => $newRoles
                        ]);
```

I get this error:
```
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `PATCH https://discordapp.com/api/v6/guilds/<#removed>/members/<#removed>` resulted in a `403 FORBIDDEN` response:

 in /pathShortened/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /pathShortened/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /pathShortened/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /pathShortened/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /pathShortened/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /pathShortened/vendor/guzzlehttp/guzzle/src/Handler/CurlM in /pathShortened/vendor/guzzlehttp/command/src/Exception/CommandException.php on line 57
```

Last time something similar happened, it was something Discord did and I was able to fix by updating restcord, but alas, I have pulled 0.3.2 and still have this issue.

**Comment by sky-lake** [comment]
Managed to figure it out -- it was a two-parter.

First, my script was passing associative arrays instead of value-only arrays to the API.  Though this worked last week, it no longer works today.  After filtering through `array_values()`, I was able to get a 400 error instead of a 403 error.

The 400 error was a result of passing mute and deaf parameters, a fix I had to reapply.  See previous issue #83 and associated [gist](https://gist.github.com/Crypta-Eve/2aa4b36585e4bc73f6fa03028e6b3b2d).

Anyway, it's working again now (until Discord changes something a third time lol).
